# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAsanawebappsuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginwgoogle(self):
    # Test name: login w/ google
    # Step # | name | target | value | comment
    # 1 | open | /-/login |  | 
    self.driver.get("https://app.asana.com/-/login")
    # 2 | setWindowSize | 1458x920 |  | 
    self.driver.set_window_size(1458, 920)
    # 3 | click | css=.ThemeableRectangularButtonPresentation--xlarge |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ThemeableRectangularButtonPresentation--xlarge").click()
    # 4 | click | css=.w1I7fb |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".w1I7fb").click()
    # 5 | assertElementPresent | xpath=//span/div/div |  | 
    elements = self.driver.find_elements(By.XPATH, "//span/div/div")
    assert len(elements) > 0
  
  def test_createproject(self):
    # Test name: create project
    # Step # | name | target | value | comment
    # 1 | open | /0/home/1205724578603564 |  | 
    self.driver.get("https://app.asana.com/0/home/1205724578603564")
    # 2 | setWindowSize | 1457x918 |  | 
    self.driver.set_window_size(1457, 918)
    # 3 | mouseOver | css=.SidebarTopNavLinks-goalsButton > .TypographyPresentation |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".SidebarTopNavLinks-goalsButton > .TypographyPresentation")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | mouseOver | linkText=web app |  | 
    element = self.driver.find_element(By.LINK_TEXT, "web app")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 6 | click | css=.ThemeableIconButtonPresentation--isEnabled:nth-child(2) > .MiniIcon > path |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ThemeableIconButtonPresentation--isEnabled:nth-child(2) > .MiniIcon > path").click()
    # 7 | click | css=.LeftIconItemStructure--isHighlighted > .TypographyPresentation |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LeftIconItemStructure--isHighlighted > .TypographyPresentation").click()
    # 8 | click | css=.DashedTile--large > .DashedTile-inner |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DashedTile--large > .DashedTile-inner").click()
    # 9 | type | id=new_project_dialog_content_name_input | project2 | 
    self.driver.find_element(By.ID, "new_project_dialog_content_name_input").send_keys("project2")
    # 10 | click | css=.PrimaryButton--standardTheme |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".PrimaryButton--standardTheme").click()
    # 11 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
  def test_openproject(self):
    # Test name: open project
    # Step # | name | target | value | comment
    # 1 | open | /0/home/1205724578603564 |  | 
    self.driver.get("https://app.asana.com/0/home/1205724578603564")
    # 2 | setWindowSize | 1460x921 |  | 
    self.driver.set_window_size(1460, 921)
    # 3 | click | css=.ContextMenuTarget-contextMenuEventListener:nth-child(1) > .ThemeableInteractiveCardPresentation--isNotSelected > .TypographyPresentation |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ContextMenuTarget-contextMenuEventListener:nth-child(1) > .ThemeableInteractiveCardPresentation--isNotSelected > .TypographyPresentation").click()
    # 4 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | assertElementPresent | css=.AsanaBaseTopbar |  | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".AsanaBaseTopbar")
    assert len(elements) > 0
  
  def test_createtaskinlist(self):
    # Test name: create task in list
    # Step # | name | target | value | comment
    # 1 | open | /0/home/1205724578603564 |  | 
    self.driver.get("https://app.asana.com/0/home/1205724578603564")
    # 2 | setWindowSize | 1458x919 |  | 
    self.driver.set_window_size(1458, 919)
    # 3 | click | css=.ContextMenuTarget-contextMenuEventListener:nth-child(1) > .ThemeableInteractiveCardPresentation--isNotSelected > .TypographyPresentation |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ContextMenuTarget-contextMenuEventListener:nth-child(1) > .ThemeableInteractiveCardPresentation--isNotSelected > .TypographyPresentation").click()
    # 4 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | css=.SecondarySplitDropdownMenuButtonA11y-leftButton |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".SecondarySplitDropdownMenuButtonA11y-leftButton").click()
    # 6 | click | xpath=//textarea |  | 
    self.driver.find_element(By.XPATH, "//textarea").click()
    # 7 | type | xpath=//textarea | some new task | 
    self.driver.find_element(By.XPATH, "//textarea").send_keys("some new task")
    # 8 | click | css=.PlaceholderAvatar > .CalendarMiniIcon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".PlaceholderAvatar > .CalendarMiniIcon").click()
    # 9 | click | xpath=//div[4]/div[5]/span |  | 
    self.driver.find_element(By.XPATH, "//div[4]/div[5]/span").click()
  
  def test_logout(self):
    # Test name: logout
    # Step # | name | target | value | comment
    # 1 | open | /0/home/1205724578603564 |  | 
    self.driver.get("https://app.asana.com/0/home/1205724578603564")
    # 2 | setWindowSize | 1458x920 |  | 
    self.driver.set_window_size(1458, 920)
    # 3 | assertElementPresent | xpath=//span/div/div |  | 
    elements = self.driver.find_elements(By.XPATH, "//span/div/div")
    assert len(elements) > 0
    # 4 | click | css=.ThemeableRectangularButtonPresentation-leftIcon > .MiniIcon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ThemeableRectangularButtonPresentation-leftIcon > .MiniIcon").click()
    # 5 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 6 | click | xpath=//span[contains(.,'Log out')] |  | 
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Log out\')]").click()
    # 7 | assertElementPresent | xpath=//span[contains(.,'To get started, please sign in')] |  | 
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'To get started, please sign in\')]")
    assert len(elements) > 0
  
